# Generated by Django 5.0.1 on 2024-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
